
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  
  name: reposyncstaging
  namespace: staging
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/Roopa-Sri3/kubernetes.git
    branch: main
    dir: /APPLICATIONS/STAGING/resources
    auth: none